hardDisk: /home/user/AM24D038/BackupSystem/example/HDD
localPC: /home/user/AM24D038/BackupSystem/example/local
verifyHDDSpace: true
marginSpace: 5GB
projects:
    - filesYAML/yamlFile1.yaml
    # - filesYAML/yamlFile2.yaml
