hardDisk: E:/PhD/BackupSystem/HDD
localPC: E:/PhD/BackupSystem/local
projects:
    - projectID: BibliographyFiles
      projectDescription: Contains references
      projectComment: Bib files
      projectEnabled: true
      verifyBackup: true
      backupInterval: 
          unit: week
          frequency: 1
      items:
          - itemID: ReferencesDB
            itemDescription: Contains references
            itemComment: Bib files
            itemClassification: validation
            itemLocation: E:/PhD/Bibliography_Files/
            itemEnabled: true
            syncPolicy: always
            excludeFolders: []
            excludeFiles: []