hardDisk: /home/user/AM24D038/BackupSystem/HDD
localPC: /home/user/AM24D038/BackupSystem/local
verifyHDDSpace: true
marginSpace: 5GB
projects:
    - filesYAML/yamlFile1.yaml
    # - filesYAML/yamlFile2.yaml